article_app/urls.py
from django.urls import path
from article_app.views import (
    HomeView,
    ArticleView,
    LoginView,
    TemplateView,
    ArticleListView,
    like_article,
    ArticleUpdateView,
)

app_name = "article_app"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login/", LoginView.as_view(), name="login_form"),
    path("create_article/", ArticleView.as_view(), name="article_form"),
    path(
        "article_succcess/",
        TemplateView.as_view(template_name="article_app/article_success.html"),
        name="article_success",
    ),
    path(
        "articles",
        ArticleListView.as_view(template_name="article_app/article_list"),
        name="article_list",
    ),
    path("articles/like/<int:pk>/", like_article, name="like_article"),
    path(
        "articles/edit/<int:pk>/",
        ArticleUpdateView.as_view(template_name="article_app/article_form.html"),
        name="edit_article",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('article_app.urls', namespace='article_page')),
]

article_app/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    article = models.TextField()
    created_by = models.CharField(max_length=100)
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

article_app/views.py
from django.shortcuts import redirect, get_object_or_404
from article_app.form import ArticleForm, LoginForm
from django.views.generic import TemplateView, FormView, ListView, UpdateView
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from article_app.models import Article

# Create your views here.


class LoginView(FormView):
    template_name = "article_app/login_form.html"
    form_class = LoginForm
    success_url = reverse_lazy("article_app:home")

    def form_valid(self, form):
        request = self.request
        user = authenticate(
            username=form.cleaned_data["name"],
            password=form.cleaned_data["password"],
        )
        if user:
            request.session["user_id"] = user.id
            return redirect(self.get_success_url())
        else:
            return redirect("article_app:login_form")


class HomeView(TemplateView):
    template_name = "article_app/base.html"

    def dispatch(self, request, *args, **kwargs):
        user_id = request.session.get("user_id")
        if not user_id:
            return redirect("article_app:login_form")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.request.session.get("user_id")
        if user_id:
            user = User.objects.get(pk=user_id)
            context["user"] = user
        return context


class ArticleView(FormView):
    template_name = "article_app/article_form.html"
    form_class = ArticleForm
    success_url = reverse_lazy("article_app:article_success")

    def form_valid(self, form):
        # Save the form data to the database
        Article.objects.create(
            title=form.cleaned_data["title"],
            article=form.cleaned_data["article"],
            created_by=form.cleaned_data["created_by"],
        )
        return super().form_valid(form)


class ArticleListView(ListView):
    model = Article
    template_name = "article_app/article_list.html"
    context_object_name = "articles"


def like_article(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.likes += 1
    article.save()
    return redirect("article_app:article_list")


class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = "article_app/article_form.html"
    success_url = reverse_lazy("article_app:article_list")

article_app/templates/article_app/article_form.html
{% extends 'article_app/base.html' %}

{% block content %}
<p>{% if form.instance.pk %}Edit{% else %}Create{% endif %} Article:</p>

<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button>Submit</button>
</form>
<a href="{% url 'article_app:article_list' %}">Back to articles</a>
{% endblock %}

article_app/templates/article_app/article_list.html
{% extends 'article_app/base.html' %}
{% block content %}
<ol>
    {% for article in articles %}
    <li>
        <h4>{{ article.title }}</h4>
        <p>{{ article.article }}</p>
        <p>Created by: {{ article.created_by }}</p>
        <p>Likes: {{ article.likes }}</p>
        <form action="{% url 'article_app:like_article' article.pk %}" method="post">
            {% csrf_token %}
            <button type="submit">Like</button>
        </form>
        <a href="{% url 'article_app:edit_article' article.pk %}">Edit</a>
    </li>
    {% endfor %}
</ol>
{% endblock %}

article_app/templates/article_app/article_success.html
{% extends 'article_app/base.html' %}
{% block content %}
<h2>Article created successfully!</h2>

<a href="{% url 'article_app:article_list' %}">List of Articles</a>
{% endblock %}

article_app/templates/article_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <header>
        <h1 class="text-center">Article Website</h1>
        <nav>
            <ul class="nav justify-content-center">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'article_app:article_form' %}">Create Article</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'article_app:article_list' %}">See list of article</a>
                </li>
              </ul>
        </nav>
        <hr>
    </header>
    <main>
        <div class="container">
            <h3>
                Welcome, {{ user }}!
            </h3>
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer class="bg-body-tertiary text-center text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
          © 2024 Copyright:
          <a class="text-body" href="https://mdbootstrap.com/">Georg Vietzke</a>
        </div>
        <!-- Copyright -->
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

article_app/templates/article_app/login_form.html
{% extends 'article_app/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button>Login</button>
</form>
{% endblock %}